name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-pre-commit.yaml@ec4c748cc49333a9067152b045fbc6a8bc0cd231
    with:
      pre-commit-config: .pre-commit-config.yaml
