name: remove-old-pr-docs

on:
  pull_request_target:
    types:
      - closed

jobs:
  get-docs-version-name:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-get-docs-version-name.yaml@ec4c748cc49333a9067152b045fbc6a8bc0cd231

  remove-old-pr-docs:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-remove-docs.yaml@ec4c748cc49333a9067152b045fbc6a8bc0cd231
    needs: get-docs-version-name
    with:
      script-ref: ec4c748cc49333a9067152b045fbc6a8bc0cd231
      mkdocs-yaml: mkdocs.yaml
      version-name: ${{ needs.get-docs-version-name.outputs.version-name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
