name: remove-old-pr-docs

on:
  pull_request_target:
    types:
      - closed

jobs:
  get-docs-version-name:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-get-docs-version-name.yaml@feef2b5395cf6de748cacc72f5ad08feea53e15a

  remove-old-pr-docs:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-remove-docs.yaml@feef2b5395cf6de748cacc72f5ad08feea53e15a
    needs: get-docs-version-name
    with:
      script-ref: feef2b5395cf6de748cacc72f5ad08feea53e15a
      mkdocs-yaml: mkdocs.yaml
      version-name: ${{ needs.get-docs-version-name.outputs.version-name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
