name: spell-check-pr

on:
  pull_request:

jobs:
  spell-check:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-spell-check.yaml@ec4c748cc49333a9067152b045fbc6a8bc0cd231
    with:
      cspell-json-url: https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/cspell/.cspell.json
