name: spell-check-pr

on:
  pull_request:

jobs:
  spell-check:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-spell-check.yaml@feef2b5395cf6de748cacc72f5ad08feea53e15a
    with:
      cspell-json-url: https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/cspell/.cspell.json
